language: python
python:
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch

cache:
  pip

# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script:
 - python manage.py test
 - python manage.py makemigrations
 - python manage.py migrate